# General display options
general:
  # Uses the custom data model numbers (please switch to item models)
  use-legacy-models: false
  # The height of display entity
  height: 1.7
  # The y-offset of display entity
  y-offset: -0.5
  # Use entity scale, instead of entity properties
  vanilla-scale: false
  vanilla-scale-multiplier: 1
  # Equip custom items (items with custom mapping) to hand
  hand: false

# Invisible item types
hide-types:
  - "minecraft:leather_horse_armor"
  - "minecraft:bone"

settings:
  debug:
    per-player-load-mappings: false
